### ISSUE TITLE
Use new vp-toolkit-models parameter interfaces

### ISSUE THREAD

**Issue by rabomarnix** [rabobank-blockchain/ula-vp-controller#1]
[Some interfaces changed](https://github.com/rabobank-blockchain/vp-toolkit-models/issues/1#issuecomment-533086584):

`IVerifiableCredential` -> `IVerifiableCredentialParams`
`IVerifiablePresentation` -> `IVerifiablePresentationParams`
`IProof` -> `IProofParams`

**Comment by jnieuwenhuijzen** [comment]
Solved with #4
